project_id = "mgizhsixrqdapzsgpgfo"

[functions.chat]
verify_jwt = false

[functions.create-wallet]
verify_jwt = false

[functions.verify-key]
verify_jwt = false

[functions.end-session]
verify_jwt = false

[functions.stats-snapshot]
verify_jwt = false
