project_id = "mgizhsixrqdapzsgpgfo"

[functions.chat]
verify_jwt = false

[functions.create-wallet]
verify_jwt = false

[functions.verify-key]
verify_jwt = false

[functions.end-session]
verify_jwt = false

[functions.stats-snapshot]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.revoke-key]
verify_jwt = false

[functions.add-funds]
verify_jwt = false

[functions.demo-chat]
verify_jwt = false

[functions.m2m-trade]
verify_jwt = false

[functions.random-challenge]
verify_jwt = false

[functions.random-pay]
verify_jwt = false
